apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "msgplatform.appname" . }}
  labels:
   type: {{ template "msgplatform.appname" . }}
  namespace: {{ template "msgplatform.namespace" . }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ default "3Gi" .Values.pvc.storage | trunc 63 | trimSuffix "-" }}
