apiVersion: v1
kind: Service
metadata:
  name: {{ template "msgplatform.appname" . }}
  namespace: {{ template "msgplatform.namespace" . }}
spec:
  selector:
     app: {{ template "msgplatform.appname" . }}
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    nodePort: {{ .Values.service.port }}
    protocol: TCP
