apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-{{ template "tomcat.appname" . }}
  namespace: {{ template "tomcat.namespace" . }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Release.Name }}-{{ template "tomcat.appname" . }}
  resources:
    requests:
      storage: {{ default "3Gi" .Values.pvc.storage | trunc 63 | trimSuffix "-" }}
