kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-{{ template "tomcat.appname" . }}
  namespace: {{ template "tomcat.namespace" . }}
provisioner: kubernetes.io/rbd
parameters:
  {{- range $key, $val := .Values.storageclass }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
